---
- name: Install pip dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pip_pkgs }}"
  become: yes

- name: Install latest pip
  pip:
    name: pip
    state: latest
  become: yes

- name: Add apt repos
  apt_repository:
    repo: "{{ item.ppa }}"
  with_items: "{{ pkgs }}"
  when: item.ppa is defined

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ pkgs }}"
  become: yes

- name: Install downloaded deb packages
  include: install_deb_pkg.yml
  with_items: "{{ deb_pkgs }}"

