---
- block:
  - name: Check if rebar is installed
    shell: which rebar

  rescue:
    - name: Download rebar binary file
      get_url:
        url: https://github.com/rebar/rebar/wiki/rebar
        dest: /usr/bin/rebar
        mode: 0755
        owner: root
        group: root
      become: yes
