---
- name: Enable network-manager reconnect service
  copy:
    src: reconnect.conf
    dest: /etc/init/reconnect-network-manager.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version == '16'

