---
pkgs:
  - { name: apt-transport-https, state: latest }
  - { name: ca-certificates, state: latest }
  - { name: dconf-tools, state: latest }
  - { name: gimp, state: latest, ppa: "ppa:otto-kesselgulasch/gimp" }
  - { name: git, state: latest, ppa: "ppa:git-core/ppa" }
  - { name: inotify-tools, state: latest }
  - { name: jq, state: latest }
  - { name: tree, state: latest }
  - { name: golang-go, state: latest }
  - { name: silversearcher-ag, state: latest }

deb_pkgs:
  -
    name: rocketchat
    state: latest
    check_cmd: 'stat /opt/rocketchat.deb'
    dest: "/opt"
    url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.2.3/rocketchat_2.2.3_amd64.deb
  -
    name: slack-desktop
    state: latest
    check_cmd: 'stat /usr/bin/slack'
    dest: "/opt"
    url: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.1.0-amd64.deb
  -
    name: sublime-text
    state: latest
    check_cmd: '/usr/bin/subl --version | grep "Build 3"'
    dest: "/opt"
    url: https://download.sublimetext.com/sublime-text_build-{{ build_version }}_amd64.deb

pip_pkgs:
  - python
  - python-setuptools
  - python-dev
  - build-essential
  - python-pip
