---
- name: Check if Rocket.Chat+ Client is installed
  stat:
    path: /opt/rocketchat/rocketchat
  register: rocketchat_binary

- block:
  - name: Download Rocket.Chat+ Client
    get_url:
      url: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-linux-x64.deb
      dest: /tmp/rocket.chat.deb

  - name: Install Rocket.Chat+
    apt:
      deb: /tmp/rocket.chat.deb
    become: yes

  when: not rocketchat_binary.stat.exists

- name: Update rocketchat app
  package:
    name: rocketchat
    state: latest
