---
- name: Create Slack directory if it doesn't already exist
  file:
    path: "{{ sublime_dir }}"
    state: directory
    mode: 0700
    owner: "{{ ansible_env.SUDO_USER }}"

- name: Check if Package Control is installed
  stat:
    path: "{{ sublime_dir }}/Package Control.sublime-package"
  register: pkg_ctrl

- name: Install Package Control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ sublime_dir }}/Package Control.sublime-package"
  when: pkg_ctrl.stat.exists == false
