---
- name: Add the new GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repo to sources list
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
    state: present
    create: yes

- name: Update apt cache
  apt: update_cache=yes

- name: Install linux-image-extra
  apt:
    name: linux-image-extra-{{ ansible_kernel }}
    state: present

- name: Install docker-engine
  apt:
    name: docker-engine
    state: latest

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ cur_user }}"
    groups: "docker"
    append: yes
  become: yes

- debug:
    msg: For docker to work without `sudo`, you will need to log out and back in

- name: Start docker service
  service:
    name: docker
    state: restarted
