- hosts: localhost
  roles:
  - { role: apt_pkgs, tags: [apt] }
  - git
  - { role: pip, tags: [pip] }
  - { role: chrome, tags: [chrome] }
  - { role: sublime, tags: [sublime] }
  - remap_keys
  - { role: elixir, tags: [elixir] }
  - { role: node, tags: [node] }
  - { role: npm, tags: [node] }
  - docker
  - { role: rebar, tags: [erlang] }
  - { role: network_manager, tags: [reconnect] }
  - { role: vbox, tags: [vbox] }
  vars_files:
    - ../vars.yml
